INSERT INTO users (username, first_name, last_name, email, `password`, active, gender, sex_pref, age, `location`, bio, last_log, avail)
VALUES ("A", "A", "A", "A@A.com", "AAAAAAAA", 1, "Male", "Female", "19", "Newlands, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 1),
        ("B", "B", "B", "B@B.com", "BBBBBBBB", 1, "Female", "Male", "29", "Newlands, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 1),
        ("C", "C", "C", "C@C.com", "CCCCCCCC", 1, "Other", "Bisexual", "39", "Newlands, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 0),
        ("D", "D", "D", "D@D.com", "DDDDDDDD", 0, "Female", "Male", "22", "Cape Town, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 0),
        ("E", "E", "E", "E@E.com", "EEEEEEEE", 1, "Male", "Male", "25", "Paarl, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 1),
        ("F", "F", "F", "F@F.com", "FFFFFFFF", 1, "Female", "Other", "69", "Johannesburg, Gauteng, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 1),
        ("G", "G", "G", "G@G.com", "GGGGGGGG", 1, "Female", "Female", "48", "Cape Town, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 1),
        ("H", "H", "H", "H@H.com", "HHHHHHHH", 1, "Male", "Other", "26", "Cape Town, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 0),
        ("I", "I", "I", "I@I.com", "IIIIIIII", 1, "Other", "Male", "42", "Stellenbosch, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 1),
        ("J", "J", "J", "J@J.com", "JJJJJJJJ", 1, "Female", "Bisexual", "31", "Rome, Lazio, Italy", "This appears to be a bio." ,CURRENT_TIMESTAMP, 1),
        ("K", "K", "K", "K@K.com", "KKKKKKKK", 1, "Male", "Bisexual", "84", "Cape Town, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 0),
        ("L", "L", "L", "L@L.com", "LLLLLLLL", 1, "Female", "Female", "55", "Rondebosch, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 1),
        ("M", "M", "M", "M@M.com", "MMMMMMMM", 0, "Female", "Male", "29", "Newlands, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 0),
        ("N", "N", "N", "N@N.com", "NNNNNNNN", 1, "Other", "Other", "28", "Kolkata, West Bengal, India", "This appears to be a bio." ,CURRENT_TIMESTAMP, 1),
        ("O", "O", "O", "O@O.com", "OOOOOOOO", 1, "Male", "Female", "24", "Cape Town, Western Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 1),
        ("P", "P", "P", "P@P.com", "PPPPPPPP", 1, "Female", "Male", "37", "Port Elizabeth, Eastern Cape, South Africa", "This appears to be a bio." ,CURRENT_TIMESTAMP, 0);
INSERT INTO users (username, first_name, last_name, email, `password`, active, last_log, avail)
VALUES ("Q", "Q", "Q", "Q@Q.com", "QQQQQQQQ", 1, CURRENT_TIMESTAMP, "1");
INSERT INTO images (img1, img2, img3, img4, img5)
VALUES ("tmp/1.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/3.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/2.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/3.png", "tmp/no_photo.png", "tmp/1.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/1.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/3.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/3.png", "tmp/2.png", "tmp/1.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/1.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/2.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/3.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/1.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/3.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/2.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/1.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/3.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png"),
        ("tmp/2.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png", "tmp/no_photo.png");
INSERT INTO tags (tag1, tag2, tag3, tag4, tag5, tag6, tag7, tag8, tag9, tag10, tag11, tag12, tag13, tag14, tag15, tag16, tag17, tag18, tag19, tag20, tag21, tag22, tag23, tag24)
VALUES (1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0),
        (0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0),
        (0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0),
        (0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0),
        (0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0),
        (0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0),
        (0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1),
        (1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
        (0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
        (0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
        (0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0),
        (0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0),
        (0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0),
        (0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0),
        (0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0),
        (0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0),
        (0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0);
